import type { Metadata } from "next";
import dynamic from "next/dynamic";
import NavBar from "./components/NavBar";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
// const NavBar = dynamic(() => import("./components/NavBar"), { ssr: false });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-3 flex flex-col justify-between`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
